name: gnome-contacts
adopt-info: gnome-contacts
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/folks/26/backends:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/folks/26/backends
  /usr/lib/evolution:
    symlink: $SNAP/usr/lib/evolution
  /usr/lib/evolution-data-server:
    symlink: $SNAP/usr/lib/evolution-data-server

slots:
  # for GtkApplication registration
  gnome-contacts:
    interface: dbus
    bus: session
    name: org.gnome.Contacts

apps:
  gnome-contacts:
    command: usr/bin/gnome-contacts
    extensions: [gnome]
    desktop: usr/share/applications/org.gnome.Contacts.desktop
    common-id: org.gnome.Contacts.desktop
    plugs:
      - browser-support
      #- camera
      - home
      - network
      - accounts-service
      - contacts-service
    #environment:
    #  DISABLE_WAYLAND: 'true'

parts:
  gnome-contacts:
    source: https://gitlab.gnome.org/GNOME/gnome-contacts.git
    source-type: git
    source-tag: '42.0'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dcamera=false # seems to be not wired... https://gitlab.gnome.org/GNOME/gnome-contacts/-/issues/236
      - -Ddocs=false
      - -Dmanpage=false
      - -Dprofile=default
      - -Dtelepathy=false
    parse-info: [usr/share/metainfo/org.gnome.Contacts.appdata.xml]
    organize:
      snap/gnome-contacts/current/usr: usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|=org.gnome.Contacts$|=${SNAP}/meta/gui/org.gnome.Contacts.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Contacts.desktop.in.in
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/hicolor/scalable/apps/org.gnome.Contacts.svg $CRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.Contacts.desktop $CRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - libedataserverui1.2-dev
      - libfolks-eds-dev
      - libchamplain-0.12-dev
      - libgoa-1.0-dev
      - libhandy-0.0-dev
      - libcheese-gtk-dev
      - libportal-dev
    stage-packages:
      - libassuan0
      - libchamplain-0.12-0
      - libgdata22
      - libgee-0.8-2
      - libgoa-1.0-0b
      - libgeocode-glib0
      - libgpm2
      - libgweather-3-16
      - libhandy-0.0-0
      - libical3
      - gstreamer1.0-plugins-good
      - libfolks26
      - libfolks-eds26
      - evolution-data-server
      - libecal-2.0-1
      - libedata-cal-2.0-1
      - libedataserver-1.2-26
      - libedataserverui-1.2-3
      - libebook-1.2-20
      - libcamel-1.2-63
      - libedata-book-1.2-26
      - libphonenumber8
      - libebackend-1.2-10
      - libprotobuf23
      - libboost-system1.74.0
      - libboost-thread1.74.0
      - libstdc++6
      - liblz4-1
      - libabsl20210324

    prime:
      - usr/lib/*/*assuan*.so.*
      - usr/lib/*/*gdata*.so.*
      - usr/lib/*/*handy*.so.*
      - usr/lib/*/*ical*.so.*
      - usr/lib/*/*gee*.so.*
      - usr/lib/*/*geocode-glib*.so.*
      - usr/lib/*/*goa*.so.*
      - usr/lib/*/*gpm*.so.*
      - usr/lib/*/*gweather*.so.*
      - usr/lib/*/*nss*.so
      - usr/lib/*/libsmime3.so
      - usr/lib/*/libssl3.so
      - usr/lib/*/libnspr4.so
      - usr/lib/*/liboauth.so.*
      - usr/lib/*/libpl*.so
      - usr/lib/*/*curl*.so.*
      - usr/lib/*/*rtmp.so.*
      - usr/lib/*/libabsl*.so.*
      - usr/lib/*/liblber-2.4.so.*
      - usr/lib/*/libldap_r-2.4.so.*
      - usr/lib/*/libsasl2.so.*
      - usr/lib/*/libgssapi.so.*
      - usr/lib/*/libheimntlm.so.*
      - usr/lib/*/libkrb5.so.*
      - usr/lib/*/libasn1.so.*
      - usr/lib/*/libhcrypto.so.*
      - usr/lib/*/libroken.so.*
      - usr/lib/*/libwind.so.*
      - usr/lib/*/libheimbase.so.*
      - usr/lib/*/libhx509.so.*
      - usr/lib/*/libfolks.so.*
      - usr/lib/*/libfolks-eds*.so.*
      - usr/lib/*/libedataserver*.so.*
      - usr/lib/*/libebook-*.so.*
      - usr/lib/*/libecal-*.so.*
      - usr/lib/*/libcamel-*.so.*
      - usr/lib/*/libedata-*.so.*
      - usr/lib/*/libphonenumber.so.*
      - usr/lib/*/libebackend-*.so.*
      - usr/lib/*/libprotobuf.so.*
      - usr/lib/*/libboost_system.so.*
      - usr/lib/*/libboost_thread.so.*
      - usr/lib/*/libstdc++.so.*
      - usr/lib/*/liblz4.so.*
      - usr/lib/*.so.*
      - usr/lib/evolution/*
      - usr/lib/evolution-data-server/*
      - usr/lib/*/folks/*
      - usr/share/*
      - usr/bin/*

  cleanup:
    after: [ gnome-contacts ]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
