name: gnome-contacts
adopt-info: gnome-contacts
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

passthrough:
  layout:
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/folks/45/backends:
      symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/folks/45/backends
    /usr/lib/evolution:
      symlink: $SNAP/usr/lib/evolution
    /usr/lib/evolution-data-server:
      symlink: $SNAP/usr/lib/evolution-data-server

slots:
  # for GtkApplication registration
  gnome-contacts:
    interface: dbus
    bus: session
    name: org.gnome.Contacts

apps:
  gnome-contacts:
    command: usr/bin/gnome-contacts
    extensions: [gnome-3-38]
    desktop: usr/share/applications/org.gnome.Contacts.desktop
    common-id: org.gnome.Contacts.desktop
    plugs:
      - browser-support
      #- camera
      - home
      - network
      - accounts-service
      - contacts-service
    #environment:
    #  DISABLE_WAYLAND: 'true'

parts:
  gnome-contacts:
    source: https://gitlab.gnome.org/GNOME/gnome-contacts.git
    source-type: git
    source-branch: gnome-3-36
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dcheese=false
      - -Ddocs=false
      - -Dmanpage=false
      - -Dprofile=default
      - -Dtelepathy=false
    parse-info: [usr/share/metainfo/org.gnome.Contacts.appdata.xml]
    organize:
      snap/gnome-contacts/current/usr: usr
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|=org.gnome.Contacts$|=${SNAP}/meta/gui/org.gnome.Contacts.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Contacts.desktop.in.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp $SNAPCRAFT_PART_SRC/data/icons/hicolor/scalable/apps/org.gnome.Contacts.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.Contacts.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - libedataserverui1.2-dev
      - libfolks-eds-dev
      - libchamplain-0.12-dev
      - libgoa-1.0-dev
      - libhandy-0.0-dev
      - libcheese-gtk-dev
    stage-packages:
      - libassuan0
      - libchamplain-0.12-0
      #- libclutter-gst-3.0-0
      - libgdata22
      - libgee-0.8-2
      - libgoa-1.0-0b
      #- libcheese8
      #- libcheese-gtk25
      - libgeocode-glib0
      - libgpm2
      - libgweather-3-16
      - libhandy-0.0-0
      - libical3
      - gstreamer1.0-plugins-good
      - libfolks25
      - libfolks-eds25
      - evolution-data-server
      - libecal-2.0-1
      - libedata-cal-2.0-1
      - libedataserver-1.2-24
      - libedataserverui-1.2-2
      - libebook-1.2-20
      - libcamel-1.2-62
      - libedata-book-1.2-26
      - libphonenumber7
      - libebackend-1.2-10
      - libprotobuf17
      - libboost-system1.67.0
      - libboost-thread1.67.0
      - libstdc++6
      - liblz4-1

    prime:
      - usr/lib/*/*assuan*.so.*
      #- usr/lib/*/*cheese*.so.*
      #- usr/lib/*/*clutter-gst*.so.*
      - usr/lib/*/*gdata*.so.*
      - usr/lib/*/*handy*.so.*
      - usr/lib/*/*ical*.so.*
      - usr/lib/*/*gee*.so.*
      - usr/lib/*/*geocode-glib*.so.*
      - usr/lib/*/*goa*.so.*
      - usr/lib/*/*gpm*.so.*
      - usr/lib/*/*gweather*.so.*
      - usr/lib/*/*nss*.so
      - usr/lib/*/libsmime3.so
      - usr/lib/*/libssl3.so
      - usr/lib/*/libnspr4.so
      - usr/lib/*/liboauth.so.*
      - usr/lib/*/libpl*.so
      - usr/lib/*/*curl*.so.*
      - usr/lib/*/*rtmp.so.*
      - usr/lib/*/liblber-2.4.so.*
      - usr/lib/*/libldap_r-2.4.so.*
      - usr/lib/*/libsasl2.so.*
      - usr/lib/*/libgssapi.so.*
      - usr/lib/*/libheimntlm.so.*
      - usr/lib/*/libkrb5.so.*
      - usr/lib/*/libasn1.so.*
      - usr/lib/*/libhcrypto.so.*
      - usr/lib/*/libroken.so.*
      - usr/lib/*/libwind.so.*
      - usr/lib/*/libheimbase.so.*
      - usr/lib/*/libhx509.so.*
      - usr/lib/*/libfolks.so.*
      - usr/lib/*/libfolks-eds*.so.*
      - usr/lib/*/libedataserver*.so.*
      - usr/lib/*/libebook-*.so.*
      - usr/lib/*/libecal-*.so.*
      - usr/lib/*/libcamel-*.so.*
      - usr/lib/*/libedata-*.so.*
      - usr/lib/*/libphonenumber.so.*
      - usr/lib/*/libebackend-*.so.*
      - usr/lib/*/libprotobuf.so.*
      - usr/lib/*/libboost_system.so.*
      - usr/lib/*/libboost_thread.so.*
      - usr/lib/*/libstdc++.so.*
      - usr/lib/*/liblz4.so.*
      - usr/lib/*.so.*
      - usr/lib/evolution/*
      - usr/lib/evolution-data-server/*
      - usr/lib/*/folks/*
      - usr/share/*
      - usr/bin/*
