name: gnome-contacts
adopt-info: gnome-contacts
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/folks/26/backends:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/folks/26/backends
  /usr/lib/evolution:
    symlink: $SNAP/usr/lib/evolution
  /usr/lib/evolution-data-server:
    symlink: $SNAP/usr/lib/evolution-data-server

slots:
  # for GtkApplication registration
  gnome-contacts:
    interface: dbus
    bus: session
    name: org.gnome.Contacts

apps:
  gnome-contacts:
    command: usr/bin/gnome-contacts
    extensions: [gnome]
    desktop: usr/share/applications/org.gnome.Contacts.desktop
    common-id: org.gnome.Contacts.desktop
    plugs:
      - browser-support
      #- camera
      - home
      - network
      - accounts-service
      - contacts-service
    #environment:
    #  DISABLE_WAYLAND: 'true'

parts:
  # required because we need a version with libsoup3
  geocode:
    source: https://gitlab.gnome.org/GNOME/geocode-glib.git
    source-tag: '3.26.4'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Denable-installed-tests=false
      - -Denable-introspection=true
      - -Denable-gtk-doc=false
      - -Dsoup2=false
    build-packages:
      - libnghttp2-dev

  # required because we need a version with libsoup3
  libgweather:
    after: [ geocode ]
    source: https://gitlab.gnome.org/GNOME/libgweather.git
    source-tag: '4.4.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Dintrospection=true
      - -Dgtk_doc=false
      - -Dtests=false
      - -Dsoup2=false
    override-pull: |
      craftctl default
      sed -i 's#CRAFT_ENV_REPLACE#/usr/lib:/usr/lib/$CRAFT_ARCH_TRIPLET#' $CRAFT_PART_SRC/data/meson.build
    build-packages:
      - gir1.2-glib-2.0

  libical:
    source: https://github.com/libical/libical.git
    source-tag: 'v3.0.17'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_LIBDIR=lib
      - -DBUILD_SHARED_LIBS:BOOL=ON
      - -DICAL_GLIB=true
      - -DGOBJECT_INTROSPECTION=true
      - -DICAL_GLIB_VAPI=true
      - -DICAL_BUILD_DOCS=false

  geoclue:
    source: https://gitlab.freedesktop.org/geoclue/geoclue.git
    source-tag: '2.7.1'
    source-depth: 1
    after: [ geocode ]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Denable-backend=false
      - -Dlibgeoclue=true
      - -Dintrospection=true
      - -Dgtk-doc=false

  evolution-data-server:
    after: [ libical, geoclue, libgweather ]
    source: https://gitlab.gnome.org/GNOME/evolution-data-server.git
    source-tag: '3.50.1'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -Doptimization=3
      - -DENABLE_CANBERRA=OFF
      - -DENABLE_GOA=ON
      - -DENABLE_DOT_LOCKING=OFF
      - -DENABLE_FILE_LOCKING=fcntl
      - -DENABLE_GTK=OFF
      - -DENABLE_GTK4=ON
      - -DENABLE_GOOGLE=OFF
      - -DENABLE_VALA_BINDINGS=ON
      - -DENABLE_WEATHER=OFF
      - -DWITH_OPENLDAP=OFF
      - -DWITH_LIBDB=OFF
      - -DENABLE_INTROSPECTION=ON
      - -DENABLE_INSTALLED_TESTS=OFF
      - -DENABLE_GTK_DOC=OFF
      - -DENABLE_EXAMPLES=OFF
      - -DENABLE_OAUTH2_WEBKITGTK4=OFF
    override-pull: |
      craftctl default
      sed -i "s|#include \"nss.h\"|#include \"nss/nss.h\"|g" src/camel/camel.c
      sed -i "s|#include <nss.h>|#include <nss/nss.h>|g" src/libedataserverui/e-certificate-widget.c
    override-stage: |
      craftctl default
      for PCFILE in "camel-1.2.pc" "libebackend-1.2.pc" "libebook-contacts-1.2.pc" "libedata-book-1.2.pc" "libedataserver-1.2.pc" "evolution-data-server-1.2.pc" "libebook-1.2.pc" "libecal-2.0.pc" "libedata-cal-2.0.pc" "libedataserverui4-1.0.pc"; do
        $CRAFT_PROJECT_DIR/scripts/fixpc.py $CRAFT_STAGE/usr/lib/pkgconfig/$PCFILE $CRAFT_STAGE
      done
      cp $CRAFT_STAGE/usr/lib/evolution-data-server/libedbus-private.so $CRAFT_STAGE/usr/lib/
    build-packages:
      - libkrb5-dev
      - gperf
      - libgoa-1.0-dev

  libfolks:
    source: https://gitlab.gnome.org/GNOME/folks.git
    source-tag: '0.15.6'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     ignore-odd-minor: true
    after: [ evolution-data-server ]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Deds_backend=true
      - -Dinstalled_tests=false
      - -Ddocs=false
      - -Dtelepathy_backend=false
      - -Dinspect_tool=false
      - -Dimport_tool=false
      - -Dtests=false
      - -Dprofiling=false
    build-packages:
      - libreadline-dev

  gnome-contacts:
    source: https://gitlab.gnome.org/GNOME/gnome-contacts.git
    source-type: git
    source-tag: '45.0'
    source-depth: 1
    after: [ libfolks ]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dcamera=false # seems to be not wired... https://gitlab.gnome.org/GNOME/gnome-contacts/-/issues/236
      - -Ddocs=false
      - -Dmanpage=false
      - -Dprofile=default
    parse-info: [usr/share/metainfo/org.gnome.Contacts.appdata.xml]
    organize:
      snap/gnome-contacts/current/usr: usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    override-build: |
      sed -i 's|=org.gnome.Contacts$|=${SNAP}/meta/gui/org.gnome.Contacts.svg|g' $CRAFT_PART_SRC/data/org.gnome.Contacts.desktop.in.in
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/hicolor/scalable/apps/org.gnome.Contacts.svg $CRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.Contacts.desktop $CRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - libportal-dev
      - libqrencode-dev
    stage-packages:
      - libqrencode4

  cleanup:
    after: [ gnome-contacts ]
    plugin: nil
    build-snaps: [core22, gtk-common-themes]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
